name: Deploy Django App to Azure Web App

on:
  push:
    branches:
      - main  # deploy when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies locally
        run: |
          python -m pip install --upgrade pip
          # Install packages into a folder included in deployment
          pip install --upgrade --target=.python_packages -r requirements.txt
          pip install gunicorn

      - name: Prepare for deployment
        run: |
          # Include installed packages in the deploy zip
          zip -r deploy.zip . -x "*.git*" "*.github*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ss-greetings    # replace with your App Service name
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deploy.zip
